# Generated by Django 6.0.5 on 2026-05-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='estado',
        ),
    ]
